name: Generate Access Token from actions

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Verify access token by listing repositories
        run: |
          curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/installation/repositories
