name: Generate Access Token from actions

on:
  workflow_call:
    # inputs:
    #   runs-on:
    #     description: 'Define the type of machine that will process the workflow. [Choosing where a workflow runs](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs)'
    #     type: string
    #     default: "['ubuntu-latest']"
    #   app-id:
    #     description: 'Git app ID'
    #     type: string
    #   private-key:
    #     description: 'Git app private-token'
    # secrets:
    #   GIT_APP_PRIVATE_KEY:
    #     required: true

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Verify access token by listing repositories
        run: |
          curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/installation/repositories
