name: Marketplace action

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub app-token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${{ steps.app-token.outputs.token }}" >> $GITHUB_ENV

      - name: Verify access token by listing repositories
        run: |
          curl -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/installation/repositories

  # use-token:
  #   runs-on: ubuntu-latest
  #   needs: generate-token
  #   steps:
  #     - uses: actions/create-github-app-token@v1
  #       id: app-token
  #       with:
  #         app-id: ${{ vars.GIT_APP_ID }}
  #         private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
  #         owner: ${{ github.repository_owner }}

  #     - name: Verify access token by listing repositories
  #       run: |
  #         curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
  #              -H "Accept: application/vnd.github.v3+json" \
  #              https://api.github.com/installation/repositories
