name: Generate GitHub App Access Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.env.outputs.access_token }}
      read-secret: ${{ steps.read-secret.outputs.encrypted_secret }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Verify access token by listing repositories
        run: |
          curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/installation/repositories


  use-token:
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Verify access token by listing repositories
        run: |
          curl -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/installation/repositories
